### ISSUE TITLE
Easier customization of the autoresponder / router per-organization

### ISSUE THREAD

**Issue by benweissmann** [tomerovadia/VoterHelpLine#243]
Each organization has different requirements for the workflow to welcome a new voter, put them through various disclaimers, and route them to a set of pods. Right now, we have a lot of special-casing in the router, and it's hard to follow.

One idea I had was to think of this as a state machine: each voter who has not yet been routed to a state pod is in one state of a customizable state machine. Each state has a set of keywords its looking for, and actions associated with those keywords.

Here's an example of what the VoteAmerica state machine could look like as YAML:

```yaml
__default__:
  - match:
      state_name: true
    actions:
      - action: assign_state
        from_message: true
      - action: reply
        message: |
          Hi, welcome to the VoteAmerica Helpline. We're connecting you to a $STATE
          volunteer.
      - action: route_voter
        state_channel: true
    goto: null
  
  - match:
      literal: HELPLINE
    actions:
      - action: reply
        message: |
          Hi, welcome to the VoteAmerica Helpline. What state are you in?
      - action: route_voter
        lobby_channel: true
    goto: state_prompt_1

  # default
  - match:
      any: true
    actions:
      - action: reply
        message: |
          Hi, welcome to the VoteAmerica Helpline. Reply HELPLINE to be connected to
          a volunteer.
    goto: helpline_prompt


helpline_prompt:
  - match:
      literal: HELPLINE
    actions:
      - action: reply
        message: |
          Great, what state are you in?
      - action: route_voter
        lobby_channel: true
    goto: state_prompt_1

  - match:
      any: true
    actions:
      - action: reply 
        message: |
          Please reply HELPLINE to be connected to a volunteer.
    goto: helpline_prompt

state_prompt_1:
  - match:
      state_name: true
    actions:
      - action: reply
        message: |
          Hi, welcome to the VoteAmerica Helpline. We're connecting you to a $STATE
          volunteer.
      - action: assign_state
        from_message: true
      - action: route_voter
        state_channel: true
    goto: null
  - match:
      any: true
    actions:
      - action: reply 
        message: |
          Sorry, I didn't understand. What state are you in?
    goto: state_prompt_2

state_prompt_2:
  - match:
      state_name: true
    actions:
      - action: reply
        message: |
          Hi, welcome to the VoteAmerica Helpline. We're connecting you to a $STATE
          volunteer.
      - action: assign_state
        from_message: true
      - action: route_voter
        state_channel: true
    goto: null
  - match:
      any: true
    actions:
      - action: reply
        message: |
          OK, I'm finding a volunteer for you.
      - action: route_voter
        national_channel: true
    goto: null
```

vs. the simpler GA Dems state machine (just a HELPLINE-to-be-connected behavior):

```yaml
__default__:
  - match:
      literal: HELPLINE
    actions:
      - action: reply
        message: |
          Hi, welcome to the Georgia Voter Helpline. We're connecting you to a volunteer.
      - action: assign_state
        state: Georgia
      - action: route_voter
        state_channel: true
    goto: null

  - match:
      any: true
    actions:
      - action: reply
        message: |
          Hi, welcome to the Georgia Voter Helpline. Reply HELPLINE to be connected.
      - action: assign_state
        state: Georgia
      - action: route_voter
        lobby_channel: true
    goto: helpline_prompt


helpline_prompt:
  - match:
      literal: HELPLINE
    actions:
      - action: reply
        message: |
          Great, we're connecting you to a volunteer.
      - action: route_voter
        state_channel: true
    goto: null

  - match:
      any: true
    actions:
      - action: reply 
        message: |
          Please reply HELPLINE to be connected to a volunteer.
    goto: helpline_prompt
```
